import '../../style/globals.css';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header className="font-extrabold">Header</header>
        {children}
        <footer>Footer</footer>
      </body>
    </html>
  );
}
